// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXvIDZh5iik_XC8Yaxkli-FuIsQk952og',
    appId: '1:559353819315:web:d67d3957a654539d4c80c6',
    messagingSenderId: '559353819315',
    projectId: 'trackme-11f8b',
    authDomain: 'trackme-11f8b.firebaseapp.com',
    storageBucket: 'trackme-11f8b.firebasestorage.app',
    measurementId: 'G-QFP6MX121X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ81DDjjMvKMixec5ceWXs1KunzdVDQU0',
    appId: '1:559353819315:android:400f0e11fa2bb6a94c80c6',
    messagingSenderId: '559353819315',
    projectId: 'trackme-11f8b',
    storageBucket: 'trackme-11f8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkch8Vp9IqM579Q69vE7yKm8ROcOyJfZI',
    appId: '1:559353819315:ios:f5e9362a5c437c684c80c6',
    messagingSenderId: '559353819315',
    projectId: 'trackme-11f8b',
    storageBucket: 'trackme-11f8b.firebasestorage.app',
    iosBundleId: 'com.example.myLocationTrakerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkch8Vp9IqM579Q69vE7yKm8ROcOyJfZI',
    appId: '1:559353819315:ios:f5e9362a5c437c684c80c6',
    messagingSenderId: '559353819315',
    projectId: 'trackme-11f8b',
    storageBucket: 'trackme-11f8b.firebasestorage.app',
    iosBundleId: 'com.example.myLocationTrakerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXvIDZh5iik_XC8Yaxkli-FuIsQk952og',
    appId: '1:559353819315:web:e4049f1f76eff3644c80c6',
    messagingSenderId: '559353819315',
    projectId: 'trackme-11f8b',
    authDomain: 'trackme-11f8b.firebaseapp.com',
    storageBucket: 'trackme-11f8b.firebasestorage.app',
    measurementId: 'G-R37HWS22B4',
  );
}
